update_all_data learned how to skip OSM update and E911 extraction

diff --git a/update_all_data b/update_all_data
--- a/update_all_data
+++ b/update_all_data
@@ -8,12 +8,14 @@ usage() {
   echo "Parallel execution requires GNU parallel."
   echo ""
   echo "Usage: "
-  echo "  $0 [-h] [-v] [-p <num>] <e911 geojson file>"
+  echo "  $0 [-h] [-v] [-p <num>] [-o] <e911 geojson file>"
   echo ""
   echo "Arguments: "
   echo "  -h        Show this help"
   echo "  -v        Verbose output"
-  echo "  -p <num>  Number of parallel conflation processes."
+  echo "  -p <num>  Number of parallel conflation processes"
+  echo "  -o        Skip update of existing OSM data"
+  echo "  -e        Skip update of E911 town files"
   echo ""
   echo "Example: "
   echo "  time $0 -v -p 8 ~/Downloads/FS_VCGI_OPENDATA_Emergency_ESITE_point_SP_v1_-3337785522220600112.geojson"
@@ -23,7 +25,9 @@ usage() {
 
 verbose=""
 processes=""
-while getopts hvp: arg;
+doOsmUpdate=true
+doE911Update=true
+while getopts hvoep: arg;
 do
   case "$arg" in
     h)
@@ -34,6 +38,12 @@ do
       ;;
     p)
       processes="-p ${OPTARG}"
+      ;;
+    o)
+      doOsmUpdate=false
+      ;;
+    e)
+      doE911Update=false
       ;;
     ?)
       echo "Invalid argument: -${OPTARG}."
@@ -47,55 +57,61 @@ if [[ "$1" == "--help" ]]; then
   usage
 fi
 
-e911file=$(realpath $1)
-if [[ ! -f "$e911file" ]]; then
-  echo "E911 geojson file not found at $e911file"
-  echo ""
-  usage
-fi
+if [[ $doE911Update ]]; then
+  e911file=$(realpath $1)
+  if [[ ! -f "$e911file" ]]; then
+    echo "E911 geojson file not found at $e911file"
+    echo ""
+    usage
+  fi
 
-firstChar=$(head -c 1 $e911file)
-lastChar=$(tail -c 1 $e911file)
-if [[ "$firstChar" != "{" || "$lastChar" != "}" ]]; then
-  echo "E911 file at $e911file does not look like GeoJSON format"
-  echo ""
-  usage
+  firstChar=$(head -c 1 $e911file)
+  lastChar=$(tail -c 1 $e911file)
+  if [[ "$firstChar" != "{" || "$lastChar" != "}" ]]; then
+    echo "E911 file at $e911file does not look like GeoJSON format"
+    echo ""
+    usage
+  fi
 fi
 
 # Get to our script directory
 cd $scriptPath
 
-# Update OSM data.
-# This lis likely to fail if OverPass is overloaded, so do this first.
-if [[ "$verbose" ]]; then
-  echo "Downloading OSM Data from Overpass"
-fi
-php -d memory_limit=1G download_osm_addresses.php
-if [ $? -ne 0 ]; then
-  echo "Downloading from OverPass failed. Please try again."
-  exit 1
+if $doOsmUpdate; then
+  # Update OSM data.
+  # This is likely to fail if OverPass is overloaded, so do this first.
+  if [[ "$verbose" ]]; then
+    echo "Downloading OSM Data from Overpass"
+  fi
+  php -d memory_limit=1G download_osm_addresses.php
+  if [ $? -ne 0 ]; then
+    echo "Downloading from OverPass failed. Please try again."
+    exit 1
+  fi
+
+  # Update our local database from the downloaded OSM data.
+  if [[ "$verbose" ]]; then
+    echo ""
+    echo "Update our local database from the downloaded OSM data"
+  fi
+  ./reload_osm_addresses.php osm_data/osm_addresses.osm
+  if [ $? -ne 0 ]; then
+    echo "Updating the local SQLite DB with OSM data failed."
+    exit 1
+  fi
 fi
 
-# Update our local database from the downloaded OSM data.
-if [[ "$verbose" ]]; then
-  echo ""
-  echo "Update our local database from the downloaded OSM data"
-fi
-./reload_osm_addresses.php osm_data/osm_addresses.osm
-if [ $? -ne 0 ]; then
-  echo "Updating the local SQLite DB with OSM data failed."
-  exit 1
-fi
-
-# Extract E911 address points into town-by-town files.
-if [[ "$verbose" ]]; then
-  echo ""
-  echo "Extracting E911 address points into town-by-town files"
-fi
-./extract_town_points.php $verbose $e911file
-if [ $? -ne 0 ]; then
-  echo "Extracting E911 address points into town-by-town files failed."
-  exit 1
+if $doE911Update; then
+  # Extract E911 address points into town-by-town files.
+  if [[ "$verbose" ]]; then
+    echo ""
+    echo "Extracting E911 address points into town-by-town files"
+  fi
+  ./extract_town_points.php $verbose $e911file
+  if [ $? -ne 0 ]; then
+    echo "Extracting E911 address points into town-by-town files failed."
+    exit 1
+  fi
 fi
 
 # Generate OSM versions of the town points
